# Generated by Django 5.1.6 on 2025-02-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('vuelo_id', models.IntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
