# Generated by Django 5.1.6 on 2025-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
