# Generated by Django 5.1.6 on 2025-02-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
